FROM

RUN apt-get update && apt-get install --no-install-recommends -y curl && \
    curl -sSfl https://get.anchore.io/syft | sh -s -- -b /usr/local/bin && \
    curl -sSfL https://get.anchore.io/grype | sh -s -- -b /usr/local/bin 

COPY requirements.txt .

CMD ["syft", "requirements.txt", "-o", "cyclonedx-json"]
